# Generated by Django 4.0.3 on 2022-05-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_webpages_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpages',
            name='url',
        ),
    ]
